version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: manik072/vlinkbackend:latest
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DATABASE_URL=postgres://postgres:root1234@db:5432/vLink?sslmode=prefer
      - JWT_SECRET=randi
    depends_on:
      db:
        condition: service_healthy
    networks:
      - vlink-network
    restart: unless-stopped

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root1234
      - POSTGRES_DB=vLink
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - vlink-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  vlink-network:
    driver: bridge