version: '3.8'

services:
  vlink-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vlink_backend
    ports:
      - "3000:3000" # Expose the app on port 8080
    env_file:
      - .env
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=vlink_db
      - JWT_SECRET=randi
    depends_on:
      - database

  database:
    image: postgres:14
    container_name: vlink_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vlink_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

#   redis:
#     image: redis:alpine
#     container_name: vlink_redis
#     ports:
#       - "6379:6379"
#     volumes:
#       - redis_data:/data

volumes:
  postgres_data:
#   redis_data:
